AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3]  # IMAGE SIZE AS PER MOBILENETV2
BATCH_SIZE: 16
EPOCHS: 1
LEARNING_RATE: 0.001
NUM_CLASSES: 7             # NUMBER OF CLASSES IN THE DATASET
INCLUDE_TOP: False
WEIGHTS: 'imagenet'